### ISSUE TITLE
Firefox Branch

### ISSUE THREAD

**Issue by paulhitz** [paulhitz/yet-another-rest-client#11]
Consider creating a branch for a customised Firefox version.

Notes:
- Does FF have an alternative to Chrome Storage? If not, local storage can be used but profile sync will be lost and request persistence will have to be much more basic.
- The UI will need to be tested in FF
- Changes should be minimised so that merges are easy
- The project site would also need to be updated with references to FF
- A MS Edge version could also be considered (once extensions are supported in that browser)
- A branch is preferred over a fork

This would be a reasonably big task.

**Comment by paulhitz** [comment]
Hold off on this until the Chrome version has gained some traction and feedback. 

The MS Edge version might be interesting because there would be very few competitors.

**Comment by paulhitz** [comment]
Firefox Simple Storage would be an option to replace Chrome Storage: https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/simple-storage

Although AFAIK it's limited to 5mb.

See also: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage

**Comment by qwertychouskie** [comment]
Just wanted to check in and say that this would be great to have, if there's any way I could help, please let me know.
