### ISSUE TITLE
Add custom method feature a bit confusing

### ISSUE THREAD

**Issue by Ashley-Waldron** [paulhitz/yet-another-rest-client#18]
Steps to Reproduce:
1. Click on the request method dropdown.
2. Verify that the Custom option looks like it's disabled rather than useable.
3. Hover over the Custom option.
4. Verify that the mouse pointer state changes from pointer to auto/text possibly reinforcing the idea that the option is disabled.
5. With the above the + icon looks like it may be the icon to click to expand a window or something to add the Custom method but when clicked it does nothing.

Expected Behaviour:
When the user clicks the Custom text it changes to a highlighted textfield. I think this action should happen when the user hovers over the Custom option rather than when they click on it because they might not click on it if they think it's disabled. Otherwise maybe modify the hover over text to say "Click here to enter a custom request method"

**Comment by paulhitz** [comment]
Good suggestion Ashley. 

So we're saying... 
-add some CSS to highlight the textfield on hover
-change the hover text

Any interest in making the change yourself? I.e. create a pull request with the update.

**Comment by Ashley-Waldron** [comment]
Sure, I can make these changes.

**Comment by paulhitz** [comment]
Fixed in the latest code. Thanks Ashley.
