### ISSUE TITLE
Refused to set unsafe header "Cookie"

### ISSUE THREAD

**Issue by opele** [paulhitz/yet-another-rest-client#73]
Tried to set a cookie. 
Fails with above message in browser console.
Using Chrome.

**Comment by paulhitz** [comment]
According to the XMLHttpRequest spec, Cookies is a "forbidden" request header. There's no easy way around this.

I've removed it and other forbidden headers from the auto-complete to avoid confusion..  

More info:
https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name
https://fetch.spec.whatwg.org/#forbidden-header-name
