### ISSUE TITLE
Postman and YARC returns different value

### ISSUE THREAD

**Issue by p2p-rigid** [paulhitz/yet-another-rest-client#94]
postman returns: 
total_value": 30307.889413990

YARC returns:
"total_value": 30307.8896,

YARC may have issue rounding up large decimals correctly

**Comment by p2p-rigid** [comment]
it would be great if you can confirm this bug

**Comment by paulhitz** [comment]
YARC is written in JavaScript. JavaScript will automatically drop trailing decimal spaces. For example, 100.00 becomes 100, 100.10 becomes 100.1 and 30307.889413990 becomes 30307.88941399. It will also convert from scientific notation in some scenarios.

However, I haven't been able to reproduce it converting 30307.889413990 to 30307.8896. Unlike the examples above, that would result in a loss of data so I would be surprised if it was valid. 

I'm going to close this issue as non-reproducible. However, if you have further examples, please let me know.
